
resources:
 repositories:
   - repository: YamlAzureDevOps
     type: GitHub
     endpoint: github.com_ankitk94
     source: ankitk94/YamlAzureDevOps
     name: ankitk94/YamlAzureDevOps
   - repository: DockerAzureFunction
     type: git
     name: DockerAzureFunction


jobs:
 - job: J1
   pool: "Default"
   steps:
      - checkout: self
      - checkout: YamlAzureDevOps
      - checkout: DockerAzureFunction
      - publish: P1/artifact1.artifact
        artifact: A1

      - publish: P1/artifact2.artifact
        artifact: A2

 - job: J2
   pool:
    name: "Default"
   steps:
      - checkout: self
      - checkout: DockerAzureFunction
      - publish: P1/artifact3.artifact
        artifact: A3


#  - deployment: deploymentJob4
#    environment: envionment4
#    dependsOn: [J1, J2]
#   #  pool: default
#    strategy:
#     runOnce:
#       deploy:
#        steps:
#         - checkout: self
#         - checkout: githubRepo1
#         - checkout: bitbucket1
#         - checkout: AzRepo1
#         - powershell: |
#             ls $(Build.ArtifactStagingDirectory)/